2025-03-06 20:25:06,748 zmirror.INFO: starting zmirror[90m     <<<<<<<<< /#/zion/zmirror/src/zmirror.py:12:<module>-><frozen importlib._bootstrap>:1360:_find_and_load-><frozen importlib._bootstrap>:1331:_find_and_load_unlocked-><frozen importlib._bootstrap>:935:_load_unlocked-><frozen importlib._bootstrap_external>:999:exec_module-><frozen importlib._bootstrap>:488:_call_with_frames_removed/#/zion/zmirror/src/zmirror_utils.py:11:<module>[0m
2025-03-06 20:25:06,773 zmirror.INFO: listening on /var/run/zmirror/zmirror_service.socket[90m     <<<<<<<<< /#/zion/zmirror/src/zmirror.py:194:<module>->/#/zion/zmirror/src/zmirror.py:177:run_command->/#/zion/zmirror/src/zmirror_daemon.py:301:daemon[0m
2025-03-06 20:27:33,194 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:27:33,195 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:27:33,196 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.pool_export",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "127946079",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "1",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:27:33+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289253 127946079",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741289253",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "pool_export",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4103",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "EXPORTED",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:27:33,196 zmirror.INFO: handling zfs event: pool_export[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:27:33,196 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.pool_export', 'ZEVENT_POOL_GUID': '0x069D2DB5B26092C8', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '127946079', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '1', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:27:33+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741289253 127946079', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741289253', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'pool_export', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'zmirror-sysfs', 'ZEVENT_EID': '4103', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'EXPORTED', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:27:33,197 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
    handle(event)
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 42, in handle
    log.info(f"zpool {cache.pool} exported")
                      ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pool'
 --- 'NoneType' object has no attribute 'pool'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:27:33,198 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:27:33,200 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:27:33,341 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:27:33,341 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:27:33,342 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.config_sync",
  "ZEVENT_POOL_GUID": "0x0000000000000000",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "256947487",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "5",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:27:33+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289253 256947487",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741289253",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "config_sync",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4104",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "UNINITIALIZED",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:27:33,342 zmirror.INFO: handling zfs event: config_sync[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:27:33,342 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:27:33,344 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:28:13,165 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,166 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,168 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.pool_import",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "40381678",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:28:13+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289293 40381678",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741289293",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "pool_import",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4107",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,168 zmirror.INFO: handling zfs event: pool_import[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:28:13,168 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:28:13,171 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:28:13,181 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,182 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,182 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.config_sync",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "40381678",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:28:13+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289293 40381678",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741289293",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "config_sync",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4106",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,183 zmirror.INFO: handling zfs event: config_sync[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:28:13,185 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:28:13,191 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:28:13,197 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,202 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,202 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "41381689",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289293",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "pool version 5000; software version unknown; uts eva 6.6.79 #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 21 12:57:28 UTC 2025 x86_64",
  "ZEVENT_TIME_STRING": "2025-03-06 20:28:13+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "import",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289293 41381689",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "51942",
  "ZEVENT_TIME_SECS": "1741289293",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4108",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,203 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:28:13,203 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:28:13,209 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,210 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:28:13,211 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,212 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "30381569",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289293",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "pool version 5000; software version unknown; uts eva 6.6.79 #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 21 12:57:28 UTC 2025 x86_64",
  "ZEVENT_TIME_STRING": "2025-03-06 20:28:13+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "open",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289293 30381569",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "51940",
  "ZEVENT_TIME_SECS": "1741289293",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4105",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,213 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:28:13,214 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:28:13,216 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:28:13,219 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,219 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,221 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:28:13,221 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,222 zmirror.INFO: {
  "UDEV_DATABASE_VERSION": "1",
  "ACTION": "change",
  "DEVPATH": "/devices/virtual/block/dm-4",
  "SUBSYSTEM": "block",
  "DEVNAME": "/dev/dm-4",
  "DEVTYPE": "disk",
  "DISKSEQ": "51",
  "SEQNUM": "4887",
  "MAJOR": "254",
  "MINOR": "4",
  "USEC_INITIALIZED": "482413247",
  "PATH": "/nix/store/79qvwdgnwd25nd43g7xy3m7cnkbrd87f-udev-path/bin:/nix/store/79qvwdgnwd25nd43g7xy3m7cnkbrd87f-udev-path/sbin",
  "TAGS": ":systemd:",
  "DM_UDEV_DISABLE_LIBRARY_FALLBACK_FLAG": "1",
  "DM_UDEV_PRIMARY_SOURCE_FLAG": "1",
  "DM_UDEV_RULES_VSN": "3",
  "DM_UDEV_DISABLE_OTHER_RULES_FLAG": "",
  "DM_NAME": "zmirror-sysfs-a",
  "DM_UUID": "CRYPT-LUKS2-2976ac53e11a426981659e884566257f-zmirror-sysfs-a",
  ".DM_SUSPENDED": "0",
  "DEVLINKS": "/dev/mapper/zmirror-sysfs-a /dev/disk/by-uuid/476587393976144584 /dev/disk/by-label/zmirror-sysfs /dev/disk/by-id/dm-name-zmirror-sysfs-a /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-2976ac53e11a426981659e884566257f-zmirror-sysfs-a /dev/disk/by-uuid",
  "ID_FS_VERSION": "5000",
  "ID_FS_LABEL": "zmirror-sysfs",
  "ID_FS_LABEL_ENC": "zmirror-sysfs",
  "ID_FS_UUID": "476587393976144584",
  "ID_FS_UUID_ENC": "476587393976144584",
  "ID_FS_UUID_SUB": "8806356902305964619",
  "ID_FS_UUID_SUB_ENC": "8806356902305964619",
  "ID_FS_BLOCKSIZE": "16384",
  "ID_FS_TYPE": "zfs_member",
  "ID_FS_USAGE": "filesystem",
  "CURRENT_TAGS": ":systemd:",
  "ID_PROCESSING": "1",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,222 zmirror.INFO: handling udev block event: change[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:135:handle[0m
2025-03-06 20:28:13,223 zmirror.WARNING: event not handled by zmirror[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:208:handle[0m
2025-03-06 20:28:13,223 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,223 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.config_sync",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "54381831",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:28:13+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289293 54381831",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741289293",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "config_sync",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4109",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,223 zmirror.INFO: handling zfs event: config_sync[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:28:13,224 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:28:13,224 zmirror.INFO: {
  "UDEV_DATABASE_VERSION": "1",
  "ACTION": "change",
  "DEVPATH": "/devices/virtual/block/zd464/zd464p1",
  "SUBSYSTEM": "block",
  "DEVNAME": "/dev/zd464p1",
  "DEVTYPE": "partition",
  "DISKSEQ": "59",
  "PARTN": "1",
  "PARTNAME": "zfs-2556973b7552cfaa",
  "SEQNUM": "4888",
  "MAJOR": "230",
  "MINOR": "465",
  "USEC_INITIALIZED": "492447901",
  "PATH": "/nix/store/79qvwdgnwd25nd43g7xy3m7cnkbrd87f-udev-path/bin:/nix/store/79qvwdgnwd25nd43g7xy3m7cnkbrd87f-udev-path/sbin",
  "TAGS": ":systemd:",
  "ID_PART_TABLE_UUID": "faa36982-dbee-a847-98b4-f60e9cff34e0",
  "ID_PART_TABLE_TYPE": "gpt",
  ".PART_SUFFIX": "-part1",
  "ID_FS_VERSION": "5000",
  "ID_FS_LABEL": "zmirror-sysfs",
  "ID_FS_LABEL_ENC": "zmirror-sysfs",
  "ID_FS_UUID": "476587393976144584",
  "ID_FS_UUID_ENC": "476587393976144584",
  "ID_FS_UUID_SUB": "1200173987706968147",
  "ID_FS_UUID_SUB_ENC": "1200173987706968147",
  "ID_FS_BLOCKSIZE": "16384",
  "ID_FS_TYPE": "zfs_member",
  "ID_FS_USAGE": "filesystem",
  "ID_PART_ENTRY_SCHEME": "gpt",
  "ID_PART_ENTRY_NAME": "zfs-2556973b7552cfaa",
  "ID_PART_ENTRY_UUID": "d4980f25-4ec8-6744-8dee-cf02ea12f99c",
  "ID_PART_ENTRY_TYPE": "6a898cc3-1dd2-11b2-99a6-080020736631",
  "ID_PART_ENTRY_NUMBER": "1",
  "ID_PART_ENTRY_OFFSET": "2048",
  "ID_PART_ENTRY_SIZE": "184320",
  "ID_PART_ENTRY_DISK": "230:464",
  "DEVLINKS": "/dev/disk/by-partlabel/zfs-2556973b7552cfaa /dev/zvol/zmirror-bak-b/sysfs-part1 /dev/disk/by-partuuid/d4980f25-4ec8-6744-8dee-cf02ea12f99c /dev/disk/by-uuid/476587393976144584 /dev/disk/by-label/zmirror-sysfs /dev/disk/by-diskseq/59-part1",
  "CURRENT_TAGS": ":systemd:",
  "ID_PROCESSING": "1",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:28:13,226 zmirror.INFO: handling udev block event: change[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:135:handle[0m
2025-03-06 20:28:13,226 zmirror.WARNING: event not handled by zmirror[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:208:handle[0m
2025-03-06 20:28:13,227 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:28:13,229 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,227 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,228 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,229 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZEVENT_HISTORY_DSID": "4526",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "136643061",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 136643061",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7168943",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4110",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "big/files@zfs-auto-snap_frequent-2025-03-06-19h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,229 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,230 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,234 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,272 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,273 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,274 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80300",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "185643610",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 185643610",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101228",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4112",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data/zion@zfs-auto-snap_frequent-2025-03-06-19h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,274 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,274 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,278 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,279 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,280 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,281 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80298",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "185643610",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 185643610",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101228",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4111",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data@zfs-auto-snap_frequent-2025-03-06-19h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,282 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,283 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,287 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,287 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,288 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,289 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80302",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "186643622",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 186643622",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101228",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4113",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-eden-data@zfs-auto-snap_frequent-2025-03-06-19h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,289 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,289 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,291 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,298 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,299 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,299 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80304",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "186643622",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 186643622",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101228",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4114",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-etzchaim-data@zfs-auto-snap_frequent-2025-03-06-19h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,300 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,300 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,301 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,607 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,608 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,609 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZEVENT_HISTORY_DSID": "4210",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "522647387",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 522647387",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7168944",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4115",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "big/files@zfs-auto-snap_frequent-2025-03-06-18h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,609 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,609 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,612 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,632 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,634 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,634 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79259",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "545647644",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 545647644",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101229",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4116",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data@zfs-auto-snap_frequent-2025-03-06-18h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,635 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,636 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,638 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,659 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,660 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,660 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79261",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "573647958",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 573647958",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101230",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4119",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data/zion@zfs-auto-snap_frequent-2025-03-06-18h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,661 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,661 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,661 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,664 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,665 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,665 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79263",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "569647913",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 569647913",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101230",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4118",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-eden-data@zfs-auto-snap_frequent-2025-03-06-18h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,666 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,666 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,668 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:30:06,669 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:30:06,669 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:30:06,670 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79265",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "566647880",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741289406",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:30:06+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741289406 566647880",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101230",
  "ZEVENT_TIME_SECS": "1741289406",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4117",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-etzchaim-data@zfs-auto-snap_frequent-2025-03-06-18h30U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:30:06,670 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:30:06,671 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:30:06,673 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:42:32,985 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:32,986 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:32,986 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_start",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "888922514",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:32+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290152 888922514",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290152",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_start",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4120",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:32,987 zmirror.INFO: handling zfs event: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:32,988 zmirror.INFO: zpool zmirror-sysfs: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:51:handle[0m
2025-03-06 20:42:32,989 zmirror.INFO: Executing command: `zpool status zmirror-sysfs`[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:48:myexec[0m
2025-03-06 20:42:32,992 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:33,007 zmirror.INFO: stdout:   pool: zmirror-sysfs[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:69:myexec[0m
2025-03-06 20:42:33,008 zmirror.INFO: stdout:  state: DEGRADED[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,008 zmirror.INFO: stdout: status: One or more devices has been taken offline by the administrator.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,009 zmirror.INFO: stdout: 	Sufficient replicas exist for the pool to continue functioning in a[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,009 zmirror.INFO: stdout: 	degraded state.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,009 zmirror.INFO: stdout: action: Online the device using 'zpool online' or replace the device with[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,010 zmirror.INFO: stdout: 	'zpool replace'.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,010 zmirror.INFO: stdout:   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar  6 20:42:32 2025[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,010 zmirror.INFO: stdout: config:[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,011 zmirror.INFO: stdout: 	NAME                          STATE     READ WRITE CKSUM[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,011 zmirror.INFO: stdout: 	zmirror-sysfs                 DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,012 zmirror.INFO: stdout: 	  mirror-0                    DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,012 zmirror.INFO: stdout: 	    zmirror-sysfs-a           ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,012 zmirror.INFO: stdout: 	    zmirror-sysfs-b           OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,013 zmirror.INFO: stdout: 	    zvol/zmirror-bak-a/sysfs  OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,013 zmirror.INFO: stdout: 	    zvol/zmirror-bak-b/sysfs  ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,013 zmirror.INFO: stdout: errors: No known data errors[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,015 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.scrub_start', 'ZEVENT_POOL_GUID': '0x069D2DB5B26092C8', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '888922514', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '0', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:42:32+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741290152 888922514', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741290152', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'scrub_start', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'zmirror-sysfs', 'ZEVENT_EID': '4120', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'ACTIVE', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:42:33,017 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 58, in handle
    re.MULTILINE)
TypeError: expected string or bytes-like object, got 'list'
 --- expected string or bytes-like object, got 'list'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:42:33,017 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:33,017 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:33,018 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "888922514",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290152",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "func=1 mintxg=0 maxtxg=52111",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:32+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan setup",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290152 888922514",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "52111",
  "ZEVENT_TIME_SECS": "1741290152",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4121",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:33,019 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:33,019 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:42:33,020 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:33,023 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:42:33,024 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:33,024 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_finish",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "915922812",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:32+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290152 915922812",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290152",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_finish",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4123",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:33,025 zmirror.INFO: handling zfs event: scrub_finish[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:33,025 zmirror.INFO: zpool zmirror-sysfs: scrub_finish[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:51:handle[0m
2025-03-06 20:42:33,026 zmirror.INFO: Executing command: `zpool status zmirror-sysfs`[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:48:myexec[0m
2025-03-06 20:42:33,038 zmirror.INFO: stdout:   pool: zmirror-sysfs[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:69:myexec[0m
2025-03-06 20:42:33,038 zmirror.INFO: stdout:  state: DEGRADED[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,039 zmirror.INFO: stdout: status: One or more devices has been taken offline by the administrator.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,039 zmirror.INFO: stdout: 	Sufficient replicas exist for the pool to continue functioning in a[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,040 zmirror.INFO: stdout: 	degraded state.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,040 zmirror.INFO: stdout: action: Online the device using 'zpool online' or replace the device with[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,040 zmirror.INFO: stdout: 	'zpool replace'.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,040 zmirror.INFO: stdout:   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar  6 20:42:32 2025[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,041 zmirror.INFO: stdout: config:[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,041 zmirror.INFO: stdout: 	NAME                          STATE     READ WRITE CKSUM[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,041 zmirror.INFO: stdout: 	zmirror-sysfs                 DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,042 zmirror.INFO: stdout: 	  mirror-0                    DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,042 zmirror.INFO: stdout: 	    zmirror-sysfs-a           ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,042 zmirror.INFO: stdout: 	    zmirror-sysfs-b           OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,043 zmirror.INFO: stdout: 	    zvol/zmirror-bak-a/sysfs  OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,043 zmirror.INFO: stdout: 	    zvol/zmirror-bak-b/sysfs  ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,043 zmirror.INFO: stdout: errors: No known data errors[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:33,044 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.scrub_finish', 'ZEVENT_POOL_GUID': '0x069D2DB5B26092C8', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '915922812', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '0', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:42:32+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741290152 915922812', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741290152', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'scrub_finish', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'zmirror-sysfs', 'ZEVENT_EID': '4123', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'ACTIVE', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:42:33,044 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 58, in handle
    re.MULTILINE)
TypeError: expected string or bytes-like object, got 'list'
 --- expected string or bytes-like object, got 'list'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:42:33,044 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:33,045 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "915922812",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290152",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "errors=0",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:32+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan done",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290152 915922812",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "52113",
  "ZEVENT_TIME_SECS": "1741290152",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4122",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:33,045 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:33,045 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:42:33,047 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:42:41,208 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:41,209 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:41,210 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_start",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "129013267",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:41+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290161 129013267",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290161",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_start",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4124",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:41,210 zmirror.INFO: handling zfs event: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:41,210 zmirror.INFO: zpool zmirror-sysfs: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:51:handle[0m
2025-03-06 20:42:41,210 zmirror.INFO: Executing command: `zpool status zmirror-sysfs`[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:48:myexec[0m
2025-03-06 20:42:41,218 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:41,223 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:41,224 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:41,226 zmirror.INFO: stdout:   pool: zmirror-sysfs[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:69:myexec[0m
2025-03-06 20:42:41,226 zmirror.INFO: stdout:  state: DEGRADED[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,227 zmirror.INFO: stdout: status: One or more devices has been taken offline by the administrator.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,227 zmirror.INFO: stdout: 	Sufficient replicas exist for the pool to continue functioning in a[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,228 zmirror.INFO: stdout: 	degraded state.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,228 zmirror.INFO: stdout: action: Online the device using 'zpool online' or replace the device with[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,228 zmirror.INFO: stdout: 	'zpool replace'.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,229 zmirror.INFO: stdout:   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar  6 20:42:41 2025[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,229 zmirror.INFO: stdout: config:[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,229 zmirror.INFO: stdout: 	NAME                          STATE     READ WRITE CKSUM[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,229 zmirror.INFO: stdout: 	zmirror-sysfs                 DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,230 zmirror.INFO: stdout: 	  mirror-0                    DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,230 zmirror.INFO: stdout: 	    zmirror-sysfs-a           ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,231 zmirror.INFO: stdout: 	    zmirror-sysfs-b           OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,231 zmirror.INFO: stdout: 	    zvol/zmirror-bak-a/sysfs  OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,231 zmirror.INFO: stdout: 	    zvol/zmirror-bak-b/sysfs  ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,232 zmirror.INFO: stdout: errors: No known data errors[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,232 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.scrub_start', 'ZEVENT_POOL_GUID': '0x069D2DB5B26092C8', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '129013267', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '0', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:42:41+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741290161 129013267', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741290161', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'scrub_start', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'zmirror-sysfs', 'ZEVENT_EID': '4124', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'ACTIVE', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:42:41,233 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 58, in handle
    re.MULTILINE)
TypeError: expected string or bytes-like object, got 'list'
 --- expected string or bytes-like object, got 'list'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:42:41,233 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:41,234 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "144013433",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290161",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "errors=0",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:41+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan done",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290161 144013433",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "52117",
  "ZEVENT_TIME_SECS": "1741290161",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4126",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:41,234 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:41,234 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:41,235 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_finish",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "144013433",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:41+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290161 144013433",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290161",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_finish",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4127",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:41,235 zmirror.INFO: handling zfs event: scrub_finish[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:41,235 zmirror.INFO: zpool zmirror-sysfs: scrub_finish[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:51:handle[0m
2025-03-06 20:42:41,236 zmirror.INFO: Executing command: `zpool status zmirror-sysfs`[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:48:myexec[0m
2025-03-06 20:42:41,246 zmirror.INFO: stdout:   pool: zmirror-sysfs[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:69:myexec[0m
2025-03-06 20:42:41,247 zmirror.INFO: stdout:  state: DEGRADED[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,247 zmirror.INFO: stdout: status: One or more devices has been taken offline by the administrator.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,247 zmirror.INFO: stdout: 	Sufficient replicas exist for the pool to continue functioning in a[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,247 zmirror.INFO: stdout: 	degraded state.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,248 zmirror.INFO: stdout: action: Online the device using 'zpool online' or replace the device with[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,248 zmirror.INFO: stdout: 	'zpool replace'.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,248 zmirror.INFO: stdout:   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar  6 20:42:41 2025[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,248 zmirror.INFO: stdout: config:[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,248 zmirror.INFO: stdout: 	NAME                          STATE     READ WRITE CKSUM[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,249 zmirror.INFO: stdout: 	zmirror-sysfs                 DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,249 zmirror.INFO: stdout: 	  mirror-0                    DEGRADED     0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,249 zmirror.INFO: stdout: 	    zmirror-sysfs-a           ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,249 zmirror.INFO: stdout: 	    zmirror-sysfs-b           OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,249 zmirror.INFO: stdout: 	    zvol/zmirror-bak-a/sysfs  OFFLINE      0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,250 zmirror.INFO: stdout: 	    zvol/zmirror-bak-b/sysfs  ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,250 zmirror.INFO: stdout: errors: No known data errors[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:41,250 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.scrub_finish', 'ZEVENT_POOL_GUID': '0x069D2DB5B26092C8', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '144013433', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '0', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:42:41+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741290161 144013433', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741290161', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'scrub_finish', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'zmirror-sysfs', 'ZEVENT_EID': '4127', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'ACTIVE', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:42:41,250 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 58, in handle
    re.MULTILINE)
TypeError: expected string or bytes-like object, got 'list'
 --- expected string or bytes-like object, got 'list'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:42:41,251 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:41,251 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x069D2DB5B26092C8",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "129013267",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290161",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "func=1 mintxg=0 maxtxg=52115",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:41+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan setup",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290161 129013267",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "52115",
  "ZEVENT_TIME_SECS": "1741290161",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "zmirror-sysfs",
  "ZEVENT_EID": "4125",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:41,251 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:41,251 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:42:41,253 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:42:55,438 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:55,438 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:55,439 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_start",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "364170030",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:55+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290175 364170030",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290175",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_start",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4128",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:55,439 zmirror.INFO: handling zfs event: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:55,439 zmirror.INFO: zpool big: scrub_start[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:51:handle[0m
2025-03-06 20:42:55,440 zmirror.INFO: Executing command: `zpool status big`[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:48:myexec[0m
2025-03-06 20:42:55,440 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:42:55,453 zmirror.INFO: stdout:   pool: big[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:69:myexec[0m
2025-03-06 20:42:55,454 zmirror.INFO: stdout:  state: ONLINE[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,454 zmirror.INFO: stdout:   scan: scrub in progress since Thu Mar  6 20:42:55 2025[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,454 zmirror.INFO: stdout: 	332M / 3.41T scanned at 332M/s, 0B / 3.41T issued[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,455 zmirror.INFO: stdout: 	0B repaired, 0.00% done, no estimated completion time[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,455 zmirror.INFO: stdout: config:[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,455 zmirror.INFO: stdout: 	NAME        STATE     READ WRITE CKSUM[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,455 zmirror.INFO: stdout: 	big         ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,456 zmirror.INFO: stdout: 	  mirror-0  ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,456 zmirror.INFO: stdout: 	    big-a   ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,456 zmirror.INFO: stdout: 	    big-b   ONLINE       0     0     0[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,456 zmirror.INFO: stdout: errors: No known data errors[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:52:handle->/#/zion/zmirror/src/zmirror_utils.py:119:get_zpool_status->/#/zion/zmirror/src/pyutils.py:121:myexec[0m
2025-03-06 20:42:55,457 zmirror.ERROR: failed to handle event: {'ZEVENT_CLASS': 'sysevent.fs.zfs.scrub_start', 'ZEVENT_POOL_GUID': '0x8D2B8D399AF9421C', 'ZED': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed', 'ZEVENT_TIME_NSECS': '364170030', 'ZEVENT_VERSION': '0', 'ZEVENT_POOL_STATE': '0', 'PWD': '/', 'ZDB': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb', 'ZEVENT_POOL_CONTEXT': '0', 'ZPOOL': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool', 'ZEVENT_TIME_STRING': '2025-03-06 20:42:55+0100', 'ZINJECT': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject', 'ZFS_VERSION': '2.2.7', 'ZEVENT_TIME': '1741290175 364170030', 'ZFS_ALIAS': 'zfs-2.2.7-1', 'SHLVL': '1', 'ZFS': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs', 'ZFS_RELEASE': '1', 'ZEVENT_TIME_SECS': '1741290175', 'IFS': ' \t\n', 'ZED_ZEDLET_DIR': '/etc/zfs/zed.d', 'ZEVENT_SUBCLASS': 'scrub_start', 'PATH': '/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin', 'ZEVENT_POOL': 'big', 'ZEVENT_EID': '4128', 'ZED_PID': '2612', 'ZEVENT_POOL_STATE_STR': 'ACTIVE', '_': '/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python', 'PYTHONNOUSERSITE': 'true', 'LC_CTYPE': 'C.UTF-8'}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:251:handle_event[0m
2025-03-06 20:42:55,457 zmirror.ERROR: Exception : Traceback (most recent call last):
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 249, in handle_event
  File "/#/zion/zmirror/src/zmirror_daemon.py", line 58, in handle
    re.MULTILINE)
TypeError: expected string or bytes-like object, got 'list'
 --- expected string or bytes-like object, got 'list'[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:252:handle_event[0m
2025-03-06 20:42:55,457 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:42:55,457 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "364170030",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290175",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "func=1 mintxg=0 maxtxg=7169095",
  "ZEVENT_TIME_STRING": "2025-03-06 20:42:55+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan setup",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290175 364170030",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7169095",
  "ZEVENT_TIME_SECS": "1741290175",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4129",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:42:55,458 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:42:55,458 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:42:55,459 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:43:05,864 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:43:05,864 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:43:05,865 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:43:05,865 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.scrub_abort",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "787284799",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_TIME_STRING": "2025-03-06 20:43:05+0100",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290185 787284799",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_TIME_SECS": "1741290185",
  "IFS": " \t\n",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "scrub_abort",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4131",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:43:05,866 zmirror.INFO: handling zfs event: scrub_abort[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:43:05,866 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:43:05,868 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:43:05,868 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:43:05,868 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "787284799",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290185",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": "errors=0",
  "ZEVENT_TIME_STRING": "2025-03-06 20:43:05+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "scan cancelled",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290185 787284799",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7169097",
  "ZEVENT_TIME_SECS": "1741290185",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4130",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:43:05,869 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:43:05,869 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:43:05,870 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:09,723 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:09,724 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:09,724 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZEVENT_HISTORY_DSID": "4531",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "665648006",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290309",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:09+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290309 665648006",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7169122",
  "ZEVENT_TIME_SECS": "1741290309",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4132",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "big/files@zfs-auto-snap_frequent-2025-03-06-19h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:09,724 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:09,725 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:09,726 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:09,850 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:09,851 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:09,852 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80769",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "770649161",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290309",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:09+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290309 770649161",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101407",
  "ZEVENT_TIME_SECS": "1741290309",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4133",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data@zfs-auto-snap_frequent-2025-03-06-19h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:09,853 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:09,854 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:09,858 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:09,864 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:09,865 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:09,865 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80775",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "771649172",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290309",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:09+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290309 771649172",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101407",
  "ZEVENT_TIME_SECS": "1741290309",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4136",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-etzchaim-data@zfs-auto-snap_frequent-2025-03-06-19h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:09,865 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:09,866 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:09,868 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:09,868 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:09,868 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:09,870 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:09,870 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80771",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "770649161",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290309",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:09+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290309 770649161",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101407",
  "ZEVENT_TIME_SECS": "1741290309",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4134",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data/zion@zfs-auto-snap_frequent-2025-03-06-19h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:09,871 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:09,871 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:09,871 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "80773",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "771649172",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290309",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:09+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "snapshot",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290309 771649172",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101407",
  "ZEVENT_TIME_SECS": "1741290309",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4135",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-eden-data@zfs-auto-snap_frequent-2025-03-06-19h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:09,872 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:09,872 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:09,874 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:10,181 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:10,182 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:10,183 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79192",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "96652746",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290310",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:10+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290310 96652746",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101408",
  "ZEVENT_TIME_SECS": "1741290310",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4138",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data@zfs-auto-snap_frequent-2025-03-06-18h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:10,183 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:10,184 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:10,186 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:10,187 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:10,191 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:10,193 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:10,196 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0x8D2B8D399AF9421C",
  "ZEVENT_HISTORY_DSID": "4753",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "93652713",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290310",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:10+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290310 93652713",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7169123",
  "ZEVENT_TIME_SECS": "1741290310",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "big",
  "ZEVENT_EID": "4137",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "big/files@zfs-auto-snap_frequent-2025-03-06-18h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:10,197 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:10,198 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:10,199 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79198",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "97652757",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290310",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:10+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290310 97652757",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101408",
  "ZEVENT_TIME_SECS": "1741290310",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4139",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-etzchaim-data@zfs-auto-snap_frequent-2025-03-06-18h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:10,201 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:10,201 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:10,204 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:10,223 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:10,224 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:10,225 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79196",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "130653120",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290310",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:10+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290310 130653120",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101409",
  "ZEVENT_TIME_SECS": "1741290310",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4140",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/vms/vm-eden-data@zfs-auto-snap_frequent-2025-03-06-18h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:10,225 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:10,226 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:10,228 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
2025-03-06 20:45:10,228 zmirror.INFO: handling client connection to client_address [90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:225:handle_client[0m
2025-03-06 20:45:10,229 zmirror.INFO: handling event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:28:handle[0m
2025-03-06 20:45:10,229 zmirror.INFO: {
  "ZEVENT_CLASS": "sysevent.fs.zfs.history_event",
  "ZEVENT_POOL_GUID": "0xD842CE6598FB0398",
  "ZEVENT_HISTORY_DSID": "79194",
  "ZED": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zed",
  "ZEVENT_TIME_NSECS": "133653153",
  "ZEVENT_VERSION": "0",
  "ZEVENT_POOL_STATE": "0",
  "PWD": "/",
  "ZEVENT_HISTORY_TIME": "1741290310",
  "ZDB": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zdb",
  "ZEVENT_POOL_CONTEXT": "0",
  "ZPOOL": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zpool",
  "ZEVENT_HISTORY_INTERNAL_STR": " ",
  "ZEVENT_TIME_STRING": "2025-03-06 20:45:10+0100",
  "ZEVENT_HISTORY_INTERNAL_NAME": "destroy",
  "ZINJECT": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zinject",
  "ZFS_VERSION": "2.2.7",
  "ZEVENT_TIME": "1741290310 133653153",
  "ZFS_ALIAS": "zfs-2.2.7-1",
  "SHLVL": "1",
  "ZFS": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/sbin/zfs",
  "ZFS_RELEASE": "1",
  "ZEVENT_HISTORY_TXG": "7101409",
  "ZEVENT_TIME_SECS": "1741290310",
  "IFS": " \t\n",
  "ZEVENT_HISTORY_HOSTNAME": "eva",
  "ZED_ZEDLET_DIR": "/etc/zfs/zed.d",
  "ZEVENT_SUBCLASS": "history_event",
  "PATH": "/nix/store/hlqp3ys2mmwvks135i8sdw0hspndik4g-zfs-user-2.2.7/bin:/nix/store/6wgd8c9vq93mqxzc7jhkl86mv6qbc360-coreutils-9.5/bin:/nix/store/7p8814g62bybwa8blmaqr9piv3vjwan5-curl-8.11.1-bin/bin:/nix/store/scgfwh3z1s3l2vhvyjsgfgx5ql552sls-gawk-5.3.1/bin:/nix/store/vniy1y5n8g28c55y7788npwc4h09fh7c-gnugrep-3.11/bin:/nix/store/yq39xdwm4z0fhx7dsm8mlpgvcz3vbfg3-gnused-4.9/bin:/nix/store/rn6iwgb2rzgmkbkvzkw8plnq00lbhbsg-net-tools-2.10/bin:/nix/store/62camdd58i8lfsv26wagljp1nqvvs4la-util-linux-2.39.4-bin/bin",
  "ZEVENT_POOL": "eva",
  "ZEVENT_EID": "4141",
  "ZED_PID": "2612",
  "ZEVENT_POOL_STATE_STR": "ACTIVE",
  "ZEVENT_HISTORY_DSNAME": "eva/data/zion@zfs-auto-snap_frequent-2025-03-06-18h45U",
  "_": "/nix/store/vlpqlmk1awvrla26c56cwgbk78l82sk2-python3-3.12.8-env/bin/python",
  "PYTHONNOUSERSITE": "true",
  "LC_CTYPE": "C.UTF-8"
}[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:29:handle[0m
2025-03-06 20:45:10,230 zmirror.INFO: handling zfs event: history_event[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:249:handle_event->/#/zion/zmirror/src/zmirror_daemon.py:36:handle[0m
2025-03-06 20:45:10,230 zmirror.INFO: writing cache[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:217:save_yaml_cache[0m
2025-03-06 20:45:10,232 zmirror.INFO: cache written.[90m     <<<<<<<<< ->/#/zion/zmirror/src/zmirror_daemon.py:255:handle_event->/#/zion/zmirror/src/zmirror_utils.py:78:save_cache->/#/zion/zmirror/src/pyutils.py:220:save_yaml_cache[0m
